### ISSUE TITLE
Problem with users signed in on CERNbox via SSO

### ISSUE THREAD

**Issue by Dimitrispant** [up2university/kuboxed#10]
During our last training, some of the participants tried to sign in on CERNbox using their Gmail accounts. However, when they signed in the interface language was on French or German and on the top bar despite their names a random token was shown like this one:

![cernbox_error](https://user-images.githubusercontent.com/13375110/39618789-fce69bdc-4f8d-11e8-9415-30ed3bfb8a7f.jpg)

**Comment by michzimny** [comment]
I think this is caused by https://github.com/up2university/single-sign-on/issues/32 and #6
