### ISSUE TITLE
Quota or upload size issue

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#11]
Gabriella reports that they have problem with quota size.  Cernbox limit is 50MB and their videos are larger than that.

**Comment by michzimny** [comment]
Is it really about the limit for the size of all stored files or rather the limit for the size of single uploads?

**Comment by ebocchi** [comment]
Quota is defined per user and it is 10GB.
I have increased the max upload size of single files from the web interface to 200MB. Is that enough?

**Comment by andreacorleto** [comment]
Maximum upload size on https://cernbox.up2university.eu/ is 50 MB. See attached screenshot 
![Screenshot_2019-03-18 Files - CERNBox](https://user-images.githubusercontent.com/36439670/54521843-163e7b80-496c-11e9-9a27-3900a4f3de31.png). On https://cernbox.test.up2university.eu/ maximum upload size is higher, I've just uploaded a video of 459 MB size and it works fine. So, the question is: to work with teachers should we use production or test instance?

**Comment by michzimny** [comment]
The test platform has been recently upgraded with a new version of the software from CERN. After we test the new version works fine in test, we will upgrade the production instance.

I think external users should stay in the production instance, and we should upgrade it very soon.
