### ISSUE TITLE
Sync client password in CERNBox

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#15]
Recently added contents to the Up2U user guide says:
> To use CERNBox to sync the files store in your computer, first you will need to go to <URL>, click on your name (top right corner), and go into settings. Take note of your username and sync client password.

I think it's not the case for Up2U. I cannot find these settings (see below).

We need to update the user guide or fix the software (or deploy a newer version of the software?).

https://cernbox.test.up2university.eu/cernbox/index.php/settings/personal#federated-cloud
![capture](https://user-images.githubusercontent.com/1483196/45150972-58bd1980-b1cd-11e8-8e45-e8adb51d11c0.PNG)

Moreover, the buttons in the left sidebar (Personal..., OAuth..., Federated...) are not clickable.

**Comment by diocas** [comment]
With the updated version of CERNBox we provide oAuth for authentication. The client will open your browser for you to login (passing through the SSO).
Already updated the documentation to mention the new process.
Closing the issue.

**Comment by michzimny** [comment]
Ok, thanks. Related to #1.
