### ISSUE TITLE
Don't start using SWAN before CERNBox!

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#16]
We have two kuboxed instances running for Up2U:
A) Test, known also as 'alpha':
http://cernbox.test.up2university.eu/cernbox/
http://swan.test.up2university.eu/
B) Production:
http://cernbox.up2university.eu/cernbox/
http://swan.up2university.eu/

They are meant to run with the same software versions and the same configurations (apart from domain names only). Maybe it's not truth as they behave differently (see below).

Steps to reproduce the issue I'm reporting:
1. Clear cookies of all up2u domains.
2. Go to Up2U SWAN. You are automatically redirected to SSO.
3. Authenticate with a Google account that has been never used with this kuboxed instance.
4. **You got SWAN page with message "403 : Forbidden ".**
5. You can go now to CERNBox of the same kuboxed instance
6. Then, it depends on which instance you're trying:
6a. In production, you get authenticated automatically.
6b. In test, you get redirected to SSO and immidietely to CERNBox standard login page (with username and password fields). You cannot do anything, so you need to clear cookies again, and get back to CERNBox again, and authenticate successfully via SSO.
7. Then you can go back to SWAN, and SWAN works fine this time.

The main issue here is no. 4. 

No. 6 is a minor side-effect, I think.

**Comment by moscicki** [comment]
Hi Michal, as far as I can tell point 4 has been always like that.

Also in our production setup at CERN which has nothing to do with Up2U users must first have CERNBox i.e. connect to the service to create their space.

http://swan.web.cern.ch:

> Having a CERNBox is a requirement to use SWAN. To activate yours connect to https://cernbox.cern.ch

**Comment by michzimny** [comment]
Kuba, then ok, I think it could stay like this, but could the error message in Up2U be more clear, i.e. express that one should go to CERNBox first, instead of saying just "Forbidden"?

**Comment by moscicki** [comment]
@diocas could you please have a look? thx.

**Comment by ebocchi** [comment]
@michzimny @diocas 
There should be a warning page saying "You don't have a CERNBox. Please go *here* and create one".

To be verified why this does not kick in

**Comment by michzimny** [comment]
More and more users are complaining about this. They want to try with SWAN, so they just go to swan...up2u...eu and it fails.

@diocas, pehaps, you could include a proper message in the incoming upgrade for SWAN?
