### ISSUE TITLE
Kernel dies after visualizing the notebook

### ISSUE THREAD

**Issue by gtoffoli** [up2university/kuboxed#17]
I accessed the SWAN service at https://swan.up2university.eu/ using the Up2U SSO authentication.
1.
To start playing with SWAN, I uploaded to my CernBox home the notebook https://github.com/explosion/spacy-notebooks/blob/master/notebooks/conference_notebooks/advanced_text_analysis.ipynb
I expected that the Jupyter kernel would not be able to execute the notebook, since it requires some Python libraries that are probably missing.
However, I met a "Dead kernel" problem at the start ("The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted .."), just after the notebook was visualized.
2.
In my CernBox home I've created a "Humanities" folder and, with a little patience, I synced it manually (*) with the github subfolder at https://github.com/callysto/callysto-sample-notebooks/tree/master/notebooks/Social_Sciences/Humanities.
Then, I've tried to start the notebook Shakespeare_and_Statistics.ipynb. And I met again the "Dead kernel" problem, after the notebook was visualized.

(*) I installed the Cernbox desktop app for Windows, but I don't know what username and password I should provide to it; moreover, while it started just after the installation, if I launch it again from the start menu it disappears immediately.

**Comment by moscicki** [comment]
Thank you for the report. We'll look into this. It's quite likely that you encountered problems since this infrastructure has been pretty much unused for a long while, so some services could be down. @diocas @michzimny

**Comment by michzimny** [comment]
@gtoffoli, does the dead kernel issue still persists?

For me, the kernel works fine, and I cannot see any difference between logs of your and mine jupyter containers. @moscicki, @diocas, if the issue persists, I can give logs, whichever you need.

@gtoffoli, regarding the desktop app, this is an issue yet to be solved - #1.

**Comment by diocas** [comment]
@michzimny logs from the containers should give us an ideia of what's happening.

**Comment by moscicki** [comment]
speculating a bit based on past experience: CVMFS is the only (?) remote runtime dependency over WAN. Would it be a good idea to put a CVMFS caching server at the PSNC data center? so that the local CVMFS caches would be filled from a local server rather than from remote location across WAN.

**Comment by gtoffoli** [comment]
@michzimny @moscicki Now the kernel issue seems to have been overcome. I am able to start both notebooks I was trying to execute. Obviously I meet execution errors due to missing Python modules.

**Comment by michzimny** [comment]
@gtoffoli, thanks for the update. 

@moscicki, I'm closing this issue, and we could discuss your suggestion in the new one #18.
