### ISSUE TITLE
CVMFS caching server at PSNC

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#18]
@moscicki said (in #17):
> speculating a bit based on past experience: CVMFS is the only (?) remote runtime dependency over WAN. Would it be a good idea to put a CVMFS caching server at the PSNC data center? so that the local CVMFS caches would be filled from a local server rather than from remote location across WAN.

I'm not sure how the WAN dependencies in CVMFS work. Is it that every spin-up of a jupyter container requires data download from CERN? Or it is just needed once for each swan-user node (i.e. kubernetes node hosting jupyter containers)?

Anyway, yes, I think we shall consider if the instances at PSNC could download all needed data just locally.

**Comment by ebocchi** [comment]
Cześć @michzimny,
Kuboxed has already a CVMFS caching server on board.
In fact, there are two levels of caches:
- the CVMFS client itself: has a local cache on the machine where the jupyter user container is spawned.
- a cluster-wise squid proxy: another container (typically running in the same pod of jupyterhub) that serves requests coming from the above CVMFS clients.

In addition, we preventively cache the (likely) most-requested resources. Specifically, the files needed to spawn a jupyter container and the libraries to create//open a python notebook.

For what concerns #17 and #19, I suspect a mount propagation problem.
I am closing this issue and following-up the others.
