### ISSUE TITLE
Kernel dies again

### ISSUE THREAD

**Issue by gtoffoli** [up2university/kuboxed#19]
Today, in my session, the Python kernel dies again as in #17, after visualizing a notebook such as Shakespeare_and_Statistics.ipynb (from callysto-sample-notebooks).

**Comment by michzimny** [comment]
@diocas, I'm sending you relevant log files via email. Please have a look what's wrong.

**Comment by diocas** [comment]
Hi @michzimny , the problem is the usual one, CVMFS is unreachable in the SWAN session.
I will have to check with CVMFS team what are these errors in the logs.
In the meantime, applying your "patch" of rebooting everything should work.

**Comment by diocas** [comment]
Just another comment, it looks like that when the CVMFS service started it was unable to reach the servers and then it stayed there for days in a broken state.

**Comment by michzimny** [comment]
I just applied my "patch". 

@gtoffoli, please check if it works for you now.

@diocas, would it be possible that you implement [Kubernetes' readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) (or any similiar solution) in kuboxed? It would enable the cluster to be aware of the fact that cvmfs daemon is not fine and will try to manage such case on its own. Currently, Kubernetes is not aware that a particular cvmfs instance does not work properly. The same could be applied to jupyter pods.

As the first step, such implementation could be very shallow, like for instance looking for known "fail" messages in the logs related to daemon's initialisation.

**Comment by gtoffoli** [comment]
Now it's working for me.

**Comment by diocas** [comment]
@michzimny I will add it to the list of improvements.
