### ISSUE TITLE
Shakespeare_and_Statistics notebook needs NLTK

### ISSUE THREAD

**Issue by gtoffoli** [up2university/kuboxed#20]
As far as I'm concerned, #19 can be closed. Thanks.

When meeting Kuba online a few days ago, I suggested to add to the Python-based LCG releases of SWAN some popular packages for natural language and text processing, such as NLTK and spaCy.
Now, willing to execute the notebooks he pointed out to the Up2U partners, I realized that Shakespeare_and_Statistics requires NLTK.
I tried to install NLTK with the shell command pip, from a cell of the notebook itself, but this failed since I cannot write into the read-only site-packages directory: I attach the modified .ipynb file including the error trace, with its extension changed to .txt
Is there a way of extending the virtual environment with new packages, for the timespan of a user session, without waiting for new LCG releases?
By the way, it seems that Shakespeare_and_Statistics requires Python 3.

NLTK (Natural Language ToolKit) is a venerable, didactically oriented, library; references: https://www.nltk.org/ and https://pypi.org/project/nltk/
spaCy is a more modern "industrial-strength" library; references: https://spacy.io/ and https://pypi.org/project/spacy/.
Both are more valuable if related data packages are also installed; see https://www.nltk.org/data.html for Installing NLTK Data and https://spacy.io/models/ for the installation of spaCy "language models".

[Shakespeare_and_Statistics_GT.txt](https://github.com/up2university/kuboxed/files/2594512/Shakespeare_and_Statistics_GT.txt)

**Comment by diocas** [comment]
Dear @gtoffoli ,
You can have Python 3 by choosing the corresponding software stack (LCG XX Python 3).
To install new packages, you need to add `--user`: https://github.com/swan-cern/help/blob/up2u/advanced/install_packages.md
These packages will be stored in CERNBox and therefore will persist across sessions.

We will check how we can provide these packages.

**Comment by gtoffoli** [comment]
Thank you @diocas.
I wasn't finding the bash terminal, since I was looking for the "terminal button" mentioned in the Help Pages. Now I've found the _Terminal_ entry it in the _New_ menu.

After installing the packages _nltk_, _TextBlob_ and _rdflib_, I managed to run the _Shakespeare_and_Statistics_ notebook without errors, but some output was missing.

I had to insert a `%matplotlib inline` instruction to display the plots.
To display the Dropdown widget it seems that I should enable a notebook extension; but I cannot find the _Nbextensions_ configuration panel; I tried to enable it from the bash terminal with the command `jupyter nbextensions_configurator enable --user`, but got an error message from the _jupyter_core/command.py_ module.

Also, when, after authentication or shutdown, I change the configuration (_LCG release_ and _Environment script_), in the configuration form I cannot find the "Always start with this configuration" checkbox.

**Comment by diocas** [comment]
Hi @gtoffoli 
Yes, it's confusing because those help pages are for the new version which is not yet deployed in UP2U. And all the things you don't see are because of that (different place for the terminal button, "always start with config" missing, lack of NbExtensions config, ...). We are currently working in the UP2U update to bring all those new functionalities.

To enable the widgets extension, you can run the following in your notebook:
`!jupyter nbextension enable --py widgetsnbextension`
After running it, refresh the page and everything should be ok.

Let me know how it goes and sorry for the confusion.
Diogo

**Comment by gtoffoli** [comment]
Hi @diocas , thank you, but when I run in my notebook the code
`!jupyter nbextension enable --py widgetsnbextension`
I get the following error
```
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_91python3/x86_64-slc6-gcc62-opt/bin/jupyter", line 4, in <module>
    from jupyter_core.command import main
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_91python3/x86_64-slc6-gcc62-opt/lib/python3.5/site-packages/jupyter_core/command.py", line 11, in <module>
    import argparse
ImportError: No module named argparse
```
although now I've installed from the terminal the _argparse_ package, with the command
`pip install --user argparse`

It is the same kind of error I got yesterday, trying to run, from the terminal, the code
`jupyter nbextensions_configurator enable --user`

**Comment by diocas** [comment]
Sorry, I forgot you are in Python3 stack.
try `!python3 -m jupyter nbextension enable --py widgetsnbextension` instead.
Let me know if it works.

**Comment by gtoffoli** [comment]
Hi @diocas , now the code for enabling the extension runs without errors. But something is still missing or there is a problem in the original notebook.
I'm attaching the notebook file after its execution (with .txt extension, since .ipybn files cannot be attached).
In cell [19], without knowing the details, I expect that line
`selector = widgets.Dropdown(options=choices, description='Select Text:')`
creates or defines a selection widget and that next line,
`interact(plot_gutenberg, ebook_no=selector)`
interacts with the user and assigns the user choice to the argument _ebook_no_ as an integer value.
But this doesn't happen; rather, the first line of the output seems the text representation of a Python object:
`<function __main__.plot_gutenberg>`
I realize that the _interact_ function produces a red error or warning message; but I cannot read it, since it immediately disappears; neither can I found the message's text inside the attached file.
Can you still help me or should I ask the notebook author at the Callysto project?
Thank you again!
[Shakespeare_and_Statistics_GT_181122.txt](https://github.com/up2university/kuboxed/files/2608450/Shakespeare_and_Statistics_GT_181122.txt)

**Comment by diocas** [comment]
Dear @gtoffoli 
Sorry for late reply. I tried it with a newer version of SWAN and the notebook was ok.
I'll try to replicate this in the version we have in UP2U to see if I can help you. We are also currently updating our software in UP2U and, hopefully, we should have news until the end of the year.

**Comment by diocas** [comment]
Dear @gtoffoli 

I've managed to get the notebook working without problems.
Here's what I had to do:
- To install missing packages:
    - Add a new cell and run `!pip install --user nltk TextBlob rdflib`.
- To display all the plots:
    - In the method `plot_text_counts` (inside _notebook_code/shakespeare.py_) replace `text_count_plt` with `plt.show()`.
- To enable notebook widgets:
    - Add a new cell and run `!python3 -m jupyter nbextension enable --py widgetsnbextension`.
    - Refresh the page to load the extension.

Let me know if you manage to get it working.
Diogo

**Comment by gtoffoli** [comment]
Hi @diocas ,
sorry, but I still have the same problem with the dropdown widget, which doesn't show, while a red error or warning message appears so briefly that I can't read it.

1. installing packages is ok: now I always get `Requirement already satisfied`
2. I've made the change you suggested inside _notebook_code/shakespeare.py_
3. enabling the widgets seems ok: se attached file `#20 181127-0.pdf`

But I noticed that the execution of
  `selector = widgets.Dropdown(options=choices, description='Select Text:')`
produces a Javascript error: I attach the JS console logs before and after the execution of the subsequent line of code
  `interact(plot_gutenberg, ebook_no=selector)`
whose execution produces the transient error message in the notebook view.
It seems that the same happens both with Chrome and FireFox.

[#20 181127-0.pdf](https://github.com/up2university/kuboxed/files/2619587/20.181127-0.pdf)
[#20 181127-1-Chrome.pdf](https://github.com/up2university/kuboxed/files/2619588/20.181127-1-Chrome.pdf)
[#20 181127-2-Chrome.pdf](https://github.com/up2university/kuboxed/files/2619590/20.181127-2-Chrome.pdf)
[#20 181127-1-FF.pdf](https://github.com/up2university/kuboxed/files/2619592/20.181127-1-FF.pdf)
[#20 181127-2-FF.pdf](https://github.com/up2university/kuboxed/files/2619594/20.181127-2-FF.pdf)

**Comment by diocas** [comment]
Dear @gtoffoli ,
I can only replicate that problem if I don't refresh the page. Did you do this step?
Diogo

**Comment by gtoffoli** [comment]
Dear @diocas , thank you,
now I've managed to get it to work, too.
I was misunderstanding "refresh the page".
I thought that you meant to re-run the notebook, possibly after restarting the kernel.
Instead, it seems like you meant that I actually reloaded the web page.
Thank you again for your patient support, Giovanni
