### ISSUE TITLE
Web analytics

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#26]
Please add Matomo tracking code to all pages as documented here:
https://wiki.geant.org/display/UP2U/Web+Analytics

How it could be achieved?

**Comment by diocas** [comment]
For SWAN easily, for CERNBox, I'll have to check, but I guess there's no problem.
I'll start looking into these issues when I finish the updates in ScienceBox.

**Comment by michzimny** [comment]
@diocas, could you please draft a timeline for this? Would you be able to share a release with such a change in February?

**Comment by diocas** [comment]
Hi Michal, we're now updating SWAN and this will be in this update. We're pointing to the end of February.

**Comment by diocas** [comment]
I've added the analytics script in the config scripts for both CERNBox and Jupyterhub.
For Jupyter, I created a specific image (built on top of the one we use in our SWAN) with the script and some extra packages to run some notebooks.
But in CERNBox Chrome is blocking me access for some reason... Need to investigate.

**Comment by michzimny** [comment]
@diocas, would it be possible to add an env variable, for instance TRACKING_CODE_URL, and use it in the customization script instead of hard-coding the URL?

As provided in the wiki page referenced above, an URL for tracking codes should be different for production and test instances.

**Comment by diocas** [comment]
Already provided.
