### ISSUE TITLE
"Your Data directory is invalid" in CERNBox/webng_beta_psnc

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#29]
I have a new instance of CERNBox deployed from scratch based on the webng_beta_psnc branch. The main page under `https://<domain>/cernbox` says:
```
Your Data directory is invalid
Check whether the data directory contains the ".ocdata" file.
```

The message above is translated from the message that I see partially in Polish:
![capture](https://user-images.githubusercontent.com/1483196/52794493-3549a500-3070-11e9-9b96-9e5ecb15e4cb.PNG)

Nothing unusual in the logs. What can I do?

**Comment by michzimny** [comment]
@diocas, when I'm downgrading file CERNBOX.yaml to its state before your 3 last commits from the branch (i.e. before "the upgrade"), then the previous version works fine. I'm clearing the cernbox and mysql volumes before launching another version of the yaml file.

**Comment by michzimny** [comment]
The same happens not only for a fresh instance but also for the instance of kuboxed that I want to upgrade. See details in email.

**Comment by moscicki** [comment]
@diocas could we please investigate?

**Comment by diocas** [comment]
I'll check the email and get back to you.

**Comment by michzimny** [comment]
It seems to be fixed by new Docker images.
