### ISSUE TITLE
error in authentication from moodle to cernbox

### ISSUE THREAD

**Issue by andreacorleto** [up2university/kuboxed#3]
Trying upload an image in Moodle (test platform) from cernbox I get this message error (error/Could not upgrade OAuth token)

**Comment by ebocchi** [comment]
Thanks for reporting.
Could be due to the externalization of Moodle configuration.
I will cross-check with the other developers.

**Comment by ebocchi** [comment]
I am for this not being fixed yet, but we are having issues with the authentication to the test instance.
I will report back asap once it is fixed and I can investigate more on the issue.

**Comment by michzimny** [comment]
@andreacorleto, I believe it is not a problem anymore?
