### ISSUE TITLE
Pod eos-mgm just stopped

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#30]
In my cluster, other than cernbox-alpha, deployed using the webng_beta_psnc branch, the eos-mgm pod just stopped. It's weird as it has restartPolicy: always. Nothing unusual can be found in /var/kubeVolumes/mgm_logs. I couldn't have found any cluster logs. I have no files like /var/log/kube-* on the master node. Nothing interesting in journalctl apart from that one message all the time (but from many days, so it's probably not relevant):

```
Feb 20 12:37:53 cernbox-beta-0 kubelet[4308]: W0220 12:37:53.069455    4308 prober.go:103] No ref for container "docker://80f2145cdacf992200f8c995b4c2b9401b9eaf2cba2a79
```

Do you know where could I find any cluster logs for a cluster installed with your InitNode.sh?

**Comment by ebocchi** [comment]
Could you also have a look at ```/var/log/messages```, please?
Any other event that could have interfered with this? E.g., VM being rebooted?

**Comment by michzimny** [comment]
Found some relevant logs in `/var/log/messages` of the node with eos-mgm:
https://pastebin.com/ubuDMf5P

It might have been related to some cluster or network issues. Kubelet report issues in reaching the master node.

I will close this issue now, and will investiage if it happens again. Thanks.

**Comment by michzimny** [comment]
Would it be an improvement to turn all EOS-related pods into deployments? Then, the cluster would managed them if they disappear for whatever reason.
