### ISSUE TITLE
"Open in SWAN" button leads to cern.ch

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#31]
Clicking the "Open in SWAN" button redirects me to something like https://swanserver.web.cern.ch/swanserver/cgi-bin/go?projurl=file://eos/docker/user/u/user6/test.ipynb

I'm using the upstream's webng_beta_psnc branch.

In previous versions of the images, I think that the SWAN_BACKEND setting was taken into account for this behaviour.

**Comment by ebocchi** [comment]
Confirmed: there is something wrong.
We'll have a look asap

**Comment by ebocchi** [comment]
The fix for this consists of
- In the CERNBox container, add to the file '/var/www/html/cernbox/config/config.php'
      'cbox.swan.url' => 'https://<HOSTNAME_OF_THE_DEPLOYMENT>/cgi-bin/go',
- In the CERNBox gateway container:
    mkdir -p /run/uwsgi
    yum -y install uwsgi-devel uwsgi-plugin-python2
    restart the uwsgi process

This will be fixed in the next release of the images.

**Comment by diocas** [comment]
I'm currently building new docker images with the fix.

**Comment by diocas** [comment]
Images pushed: cernbox and cernboxgateway. still webng_beta_psnc tag.
Please try it and close it if it's ok.

**Comment by michzimny** [comment]
I've pulled the new images and restarted pods. It works. Thanks.
