### ISSUE TITLE
Moodle integration fails with the new CERNBox

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#33]
When trying to add a file from CERNBox to Moodle, via the integration, a CERNBox window opens up and says:
> Request not valid
> This request is not valid. Please contact the administrator if this error persists.

I'm using 
learn.test.up2university.eu
and cernbox.test.up2university.eu

@diocas, I will share some secret details with you via email.

**Comment by diocas** [comment]
Can you enroll me in some course and explain where I should see the CBox integration?

**Comment by michzimny** [comment]
This is probably because of new credentials. Investigating on the Moodle side.

**Comment by diocas** [comment]
With the new credentials it works. Missing implementation on CERNBox API to allow share with oAuth (since adding a file link requires it)

**Comment by diocas** [comment]
Should be working with the updated version: gitlab-registry.cern.ch/cernbox/boxedhub/cernbox:v1.1
Please test and close this if you don't find any problem.

**Comment by michzimny** [comment]
It's now being tested by Pasquale on the Moodle side.
