### ISSUE TITLE
Some SWAN urls leading to CERN instances

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#34]
At swan.test.up2university.eu, after the new version of SWAN had been deployed, 1-2 weeks ago, I experienced SWAN being unable to start a session. I cannot reproduce it, so it's not an issue right now. But I saw then the following error message:

> SWAN could not start a session for your user, please try again. If the problem persists, please check:
   Do you have a CERNBox account? If not, click here.
   Is there a problem with the service? Find information here.
   If none of the options apply, please open a Support Ticket.

The "here" links led to CERN instances, e.g. https://cernbox.cern.ch/

They should rather point at the paired CERNBox instance at PSNC (cernbox.test.up2u...).

**Comment by michzimny** [comment]
The same happens for the current version of SWAN, for instance when it fails to spawn a kernel.

**Comment by diocas** [comment]
What do you mean by "when it fails to spawn a kernel"?
When I tried to start a session, I was unable and then got blocked. Manual actions are necessary (restart jupyterhub, inside the jupyterhub container). But hopefully this is fixed in the update I want to push this week.

**Comment by michzimny** [comment]
> What do you mean by "when it fails to spawn a kernel"?

I mean when it fails to spawn the jupyter-user* container. Regarding the spawn fail, I will report it separately soon.

**Comment by diocas** [comment]
This issue should be fixed with the update I sent you today.

**Comment by michzimny** [comment]
Other situation, when I see these errors, also in the latest version, is when one tries to launch jupyter to quickly after deployment of a new version. Then, the swanuser image is not yet fully downloaded, so it fails to start before the timeout of 30 secs.

**Comment by diocas** [comment]
That is true, but giving some waiting time before opening the gates to the public should be enough to solve it.
I'm closing this issue but re-open it if you think these problems are not solved.
