### ISSUE TITLE
SWAN cannot start session

### ISSUE THREAD

**Issue by gtoffoli** [up2university/kuboxed#42]
@Kuboxed, Hi, I wasn't able to start a SWAN session on the production server today, 5-6 weeks after the previous time.
In the configuration I specified as Software stack, in turn, "95a Python3", "94 Python3" and "Bleeding Edge Python3", with and without the Environment script "CERNBOX_HOME/myscript.sh".

I attach 2 small images for the configuration and the error message ("SWAN could not start a session for your user, please try again. If the problem persists, please check: Do you have a CERNBox account? If not, click here. Check with the service manager that SWAN is running properly.")

![configuration](https://user-images.githubusercontent.com/983587/70809240-a7d6fe80-1dc1-11ea-9246-b8ee775192d3.png)
![error message](https://user-images.githubusercontent.com/983587/70809241-a7d6fe80-1dc1-11ea-8a44-34745b466f07.png)

On the other hand, I can access my CERNBox home.

Thanks. Giovanni

**Comment by michzimny** [comment]
I have had the same issue. I just restarted some components on the server. It works fine for me now.

Please try again and reopen the issues if the problem persists.

**Comment by diocas** [comment]
Hi Giovanni,
The service should be back on. There was a component that needed to be restarted.
Diogo
