### ISSUE TITLE
After login via Google I don't see my first name

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#6]
I see a sort of code instead of my first name. Field matching problem? In CERNBox or in SSO?

Here:
![capture](https://user-images.githubusercontent.com/1483196/37657593-bc7c9e12-2c4b-11e8-8fcd-8d9fc7eebf2d.PNG)

and there:
![capture2](https://user-images.githubusercontent.com/1483196/37657606-c3d9e49e-2c4b-11e8-8465-c92729ae6060.PNG)

**Comment by ebocchi** [comment]
This is what I get from the SSO:
displayName is empty
givenName is ": TWljaGHFgg=="
surname is "Zimniewicz"

When the displayname is empty, we build "your" name as givenName + surname.

Could @foobarable check what is there on the SSO side?

**Comment by foobarable** [comment]
@ebocchi Which instance?

**Comment by michzimny** [comment]
https://cernbox.test.up2university.eu/cernbox

**Comment by foobarable** [comment]
Can you check https://cernbox.test.up2university.eu/cernbox/Shibboleth.sso/Session

After I log in via edugain my session looks like this:

Attributes
eppn: 1 value(s)
givenName: 1 value(s)
mail: 1 value(s)
sn: 1 value(s)
uid: 1 value(s)

![screenshot-2018-3-20 personlich - cernbox](https://user-images.githubusercontent.com/893335/37659379-1944f1ea-2c50-11e8-8f87-f1871ede75b2.png)

**Comment by ebocchi** [comment]
I have 
```
Attributes
givenName: 1 value(s)
mail: 1 value(s)
sn: 1 value(s)
uid: 1 value(s)
```

![screenshot from 2018-03-20 15-07-09](https://user-images.githubusercontent.com/16349448/37659477-6b1d27bc-2c50-11e8-8c7e-8200ea3328df.png)

**Comment by foobarable** [comment]
eMail Mapping seems wrong, also which authsource did @michzimny use for his result?

**Comment by michzimny** [comment]
> eMail Mapping seems wrong, also which authsource did @michzimny use for his result?

Google

> https://cernbox.test.up2university.eu/cernbox/Shibboleth.sso/Session

I have:
```
Attributes
givenName: 1 value(s)
mail: 1 value(s)
sn: 1 value(s)
uid: 1 value(s)
```

**Comment by ebocchi** [comment]
Yes, we are not showing the right email but the internally-mapped account name.
However, this does not impact the display name issue reported by michzimny

**Comment by foobarable** [comment]
@michzimny Can you please log in via google at oc.test.up2university.eu and send me the output of https://oc.test.up2university.eu/Shibboleth.sso/Session?

**Comment by michzimny** [comment]
Sent by mail.

**Comment by foobarable** [comment]
Found the reason. Our LDAP stores names with special characters like this. We have to decode before we pass the attribute.

**Comment by michzimny** [comment]
I move the issue to the SSO project: https://github.com/up2university/single-sign-on/issues/32

**Comment by ebocchi** [comment]
Fixed!
It was due to inconsistent representation of special characters (mixed plain and utf-8 encoded form SSO and base64 encoding in LDAP)

**Comment by michzimny** [comment]
It works, thanks!
