### ISSUE TITLE
Different files in CERNBox/SWAN and unable to upload files

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#7]
I can add files through SWAN but they're not visible in CERNBox. In CERNBox I see no files. 

Trying to upload a file to CERNBox, I get:

> Error uploading file "29496836_1641846639233469_3798226767412461568_o.jpg": Not enough free space, you are uploading 258 KB but only 0 B is left"

For the latter problem, maybe I have quota 0 and SWAN does not check the quota? 

I tested with Google and EduGAIN accounts. Everything at cernbox/swan.test instance.

**Comment by ebocchi** [comment]
Could you please try again now?
It could have been due to the lost VM and a not cleaned-up permission on the EOS side.

**Comment by michzimny** [comment]
It's much better now. 

Shall we document the procedure you undertook for administrators?

**Comment by ebocchi** [comment]
It was a sort of "emergency" procedure to unstuck this misconfigured bit. It should not be required, even in the case a container fails. In case of unexpected failures of the VMs or something down in the infrastructure, it can be useful to deploy --> delete --> re-deploy. The delete will clear inconsistencies that could impact the functionality of the service.

The documentation will be updated with the new deployment model of EOS (in the making). I will keep track of issues that require documentation.
