### ISSUE TITLE
Problem sharing Swan notebook

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#8]
I have prepared a simple notebook in Swan. Then I create a shareable URL for it in CERNBox:
https://cernbox.test.up2university.eu/cernbox/index.php/s/JZxivocF6kOepo1

The URL does not work for me if I am not authenticated. The page says about an error and refreshes every 5 secs.

**Comment by ebocchi** [comment]
Strange...
This is what I see by just clicking the link above (and I am not authenticated either):
![screenshot from 2018-04-17 14-55-58](https://user-images.githubusercontent.com/16349448/38870902-81e2fd36-424f-11e8-8f91-cc00c859692b.png)

**Comment by michzimny** [comment]
The URL works for me only if I'm authenticated. I have tried in private windows in Firefox, Chrome, and Opera, two different machines.

![screenshot-2018-4-17 cernbox](https://user-images.githubusercontent.com/1483196/38873912-2a56a1a0-4257-11e8-8178-c3956832374c.png)

When I click the red [x] then I see the download button but the page keeps refreshing itself every 5 secs.

**Comment by ebocchi** [comment]
Fixed: Wrong shibboleth configuration for SWAN viewer app.
The container runs on a temporary fix (will be wiped on restart).
I am updating the container image (tag will NOT change) to have the correct configuration on board.

**Comment by michzimny** [comment]
Yes, it works now.

@ebocchi, could you please let me know after your update is ready? I'd like to be sure that I can safely restart the services.

**Comment by ebocchi** [comment]
I am building the image right now. Say 30minutes, the new one will be there.
This is tagged cernbox:v0.7
Make sure imagePullPolicy is set to Always or pull the image manually on the box, otherwise kubernetes won't fetch the new one.

**Comment by ebocchi** [comment]
Pushed
