### ISSUE TITLE
Add a shared file to own owncloud

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#9]
Steps to reproduce:
* Have a share URL to a file in CERNBox
* Open the URL being authenticated as another user
* Click "Add to your owncloud" button in top right corner
* Paste: https://cernbox.test.up2university.eu/cernbox/
* Press Enter
* In the dialog box click "Add remote share"

Expected outcome: the file gets added to my account.

Actual outcome: message "Couldn't add remote share"

**Comment by michzimny** [comment]
@moscicki reports that CERNBox has not been using this feature at all. Maybe it should be hidden then.

**Comment by michzimny** [comment]
Could we hide the option?

**Comment by michzimny** [comment]
Just a kind reminder :)

**Comment by moscicki** [comment]
FYI @diocas

**Comment by diocas** [comment]
This is not present in the new version.
Closing the issue.
